spring:
  application:
    name: todoring-server
  profiles:
    include: secrets
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create # ??? update? ??
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    org:
      springframework: info